config/routes.rb
Rails.application.routes.draw do
  resources :admins
#  devise_for :users
  get 'home/feedback'
  get 'home/feedbacks'
  post 'home/submitfeedback'
  get 'home/unauthorized'

  resources :questions do 
    resources :choices
  end
  resources :emails

  devise_for :users , :controllers => { :registrations => "users/registrations" }
  resources :profiles
  
  root 'home#feedback'   
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :authenticate_admin, only: :index

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)
    @user = User.find_by(id: current_user.id)
    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      if Profile.exists?(user_id: current_user.id)
        @profile = Profile.find_by(user_id: current_user.id)
      else
        redirect_to new_profile_path
        flash[:notice] = "You haven't created profile yet. Please create a profile here."
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:place, :phonenumber, :degree1p, :degree1c, :degree1branch, :degree2p, :degree2c, :degree2branch, :twelvep, :twelvec, :twelveplace, :tenthp, :tenthc, :tenths, :technicalskills, :nontechnicalskills, :analyticalskills, :projects, :coursestaken, :goodat, :dreamjob, :awards, :internship, :user_id)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_for(profile) do |f| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="col-md-10 col-md-offset-1">
  <div class="form-group form-group">
    <%= f.label :present_place %>
    <%= f.text_field :place , :class => "form-control"%>
  </div>

  <div class="form-group">
    <%= f.label :phone_number %>
    <%= f.text_field :phonenumber , :class => "form-control"%>
  </div>

  <div class="form-group">
    <label>10th Percentage</label>
    <%= f.text_field :tenthp , :class => "form-control"%>
  </div>

  <div class="form-group">
    <label>10th School</label>
    <%= f.text_field :tenths , :class => "form-control"%>
  </div>

  <div class="form-group">
    <label>10th Place</label>
    <%= f.text_field :tenthc , :class => "form-control"%>
  </div>

  <div class="form-group">
    <label>12th Percentage</label>
    <%= f.text_field :twelvep , :class => "form-control"%>
  </div>

  <div class="form-group">
    <label>12th College</label>
    <%= f.text_field :twelvec , :class => "form-control"%>
  </div>

  <div class="form-group">
    <label>12th Place</label>
    <%= f.text_field :twelveplace , :class => "form-control"%>
  </div>

  <div class="form-group">
    <label>Degree 1 Percentage</label>
    <%= f.text_field :degree1p , :class => "form-control"%>
  </div>

  <div class="form-group">
    <label>Degree 1 College</label>
    <%= f.text_field :degree1c , :class => "form-control"%>
  </div>

  <div class="form-group">
    <label>Degree 1 Branch</label>
    <%= f.text_field :degree1branch , :class => "form-control"%>
  </div>

  <div class="form-group">
    <label>Degree 2 Percentage</label>
    <%= f.text_field :degree2p , :class => "form-control"%>
  </div>

  <div class="form-group">
    <label>Degree 2 College</label>
    <%= f.text_field :degree2c , :class => "form-control"%>
  </div>

  <div class="form-group">
    <label>Degree 2 Branch</label>
    <%= f.text_field :degree2branch , :class => "form-control"%>
  </div>


  <div class="form-group">
    <%= f.label :technical_skills %>
    <%= f.text_area :technicalskills , :class => "form-control"%>
  </div>

  <div class="form-group">
    <%= f.label :non_technical_skills %>
    <%= f.text_area :nontechnicalskills , :class => "form-control"%>
  </div>

  <div class="form-group">
    <%= f.label :analytical_skills %>
    <%= f.text_area :analyticalskills , :class => "form-control"%>
  </div>

  <div class="form-group">
    <%= f.label :projects %>
    <%= f.text_area :projects , :class => "form-control"%>
  </div>

  <div class="form-group">
    <%= f.label :courses_taken %>
    <%= f.text_area :coursestaken , :class => "form-control"%>
  </div>

  <div class="form-group">
    <%= f.label :good_at %>
    <%= f.text_area :goodat , :class => "form-control"%>
  </div>

  <div class="form-group">
    <%= f.label :dream_job %>
    <%= f.text_area :dreamjob , :class => "form-control"%>
  </div>

  <div class="form-group">
    <%= f.label :awards %>
    <%= f.text_area :awards , :class => "form-control"%>
  </div>

  <div class="form-group">
    <%= f.label :internship %>  
    <%= f.text_area :internship , :class => "form-control"%>
  </div>

  <%= f.hidden_field :user_id, :value => current_user.id %> 

  <div class="actions">
    <%= f.submit :Submit, :class => "btn btn-info btn-raised" %>
  </div>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<div class="container-fluid order">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="well well-md">
        <fieldset>
          <legend class="text-center">Edit Profile</legend>
            <%= render 'form', profile: @profile %>
        </fieldset>
      </div>
    </div>
  </div>
</div>
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <div class="well well-md a">
        <fieldset>
          <legend class="text-center">Profiles</legend>
        </fieldset>
        <table>
          <thead>
            <tr>
              <th>User Name</th>
              <th>User Email</th>
              <th>Place</th>
              <th>Phone Number</th>
              <th>Degree1 Percentage</th>
              <th>Degree1 College</th>
              <th>Degree1 Branch</th>
              <th>Degree2 Percentage</th>
              <th>Degree2 college</th>
              <th>Degree2 Branch</th>
              <th>Twelvth Percentage</th>
              <th>Twelvth College</th>
              <th>Twelvth Place</th>
              <th>Tenth Percentage</th>
              <th>Tenth College</th>
              <th>Tenth Place</th>
              <th>Technical Skills</th>
              <th>Nontechnical Skills</th>
              <th>Analytical Skills</th>
              <th>Projects</th>
              <th>Courses taken</th>
              <th>Good at</th>
              <th>Dream Job</th>
              <th>Awards</th>
              <th>Internship</th>
            </tr>
          </thead>

          <tbody>
            <% @profiles.each do |profile| %>
              <tr>
                <% @user = User.find_by(id: profile.user_id) %>
                <% @email = Email.find_by(email: @user.email) %>
                <td><%= @email.user_name %></td>
                <td><%= @email.email %></td>
                <td><%= profile.place %></td>
                <td><%= profile.phonenumber %></td>
                <td><%= profile.degree1p %></td>
                <td><%= profile.degree1c %></td>
                <td><%= profile.degree1branch %></td>
                <td><%= profile.degree2p %></td>
                <td><%= profile.degree2c %></td>
                <td><%= profile.degree2branch %></td>
                <td><%= profile.twelvep %></td>
                <td><%= profile.twelvec %></td>
                <td><%= profile.twelveplace %></td>
                <td><%= profile.tenthp %></td>
                <td><%= profile.tenthc %></td>
                <td><%= profile.tenths %></td>
                <td><%= profile.technicalskills %></td>
                <td><%= profile.nontechnicalskills %></td>
                <td><%= profile.analyticalskills %></td>
                <td><%= profile.projects %></td>
                <td><%= profile.coursestaken %></td>
                <td><%= profile.goodat %></td>
                <td><%= profile.dreamjob %></td>
                <td><%= profile.awards %></td>
                <td><%= profile.internship %></td>
                <!--td><%= link_to 'Show', profile %></td>
                <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
                <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td-->
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/profiles/new.html.erb
<div class="container-fluid order">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="well well-md">
        <fieldset>
          <legend class="text-center">New Profile</legend>
            <%= render 'form', profile: @profile %>
        </fieldset>
      </div>
    </div>
  </div>
</div>
<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
 <section class="section">
 <div class="container-fluid">
    <div class="row">
      <div class="col-md-8 col-md-offset-2 a">
        <div class="well well-md a">
          <fieldset>
            <div class="row">
              <div class="col-md-3 col-md-offset-2 col-xs-1"><legend><strong>My Profile</strong></legend></div>
              <%= link_to edit_profile_path(@profile) do %>
                <div class="col-xs-1 col-md-2"><i class="material-icons">mode_edit</i></div>
              <% end -%>
            </div>
              <br><br><br>
            <div class="row">
              <div class="col-md-1 col-xs-1"><strong>Place:</strong></div>
              <div class="col-md-2 col-xs-2"><%= @profile.place %></div>
            </div><br>

            <div class="row">
              <div class="col-md-1 col-xs-1"><strong>Phonenumber:</strong></div>
              <div class="col-md-2 col-xs-2"><%= @profile.phonenumber %></div>
            </div><br>

            <div class="row">
              <div class="col-md-1 col-xs-1"><strong>Degree1 Percentage:</strong></div>
              <div class="col-md-2 col-xs-2"><%= @profile.degree1p %></div>
            </div><br>

            <div class="row">
              <div class="col-md-1 col-xs-1"><strong>Degree1 College:</strong></div>
              <div class="col-md-2 col-xs-2"><%= @profile.degree1c %></div>
            </div><br>

            <div class="row">
              <div class="col-md-1 col-xs-1"><strong>Degree1 Branch:</strong></div>
              <div class="col-md-2 col-xs-2"><%= @profile.degree1branch %></div>
            </div><br>

            <div class="row">
              <div class="col-md-1 col-xs-1"><strong>Degree2 Percentage:</strong></div>
              <div class="col-md-2 col-xs-2"><%= @profile.degree2p %></div>
            </div><br>

            <div class="row">
              <div class="col-md-1 col-xs-1"><strong>Degree2 College:</strong></div>
              <div class="col-md-2 col-xs-2"><%= @profile.degree2c %></div>
            </div><br>

            <div class="row">
              <div class="col-md-1 col-xs-1"><strong>Degree2 Branch:</strong></div>
              <div class="col-md-2 col-xs-2"><%= @profile.degree2branch %></div>
            </div><br>

            <div class="row">
              <div class="col-md-1 col-xs-1"><strong>Twelve Percentage:</strong></div>
              <div class="col-md-2 col-xs-2"><%= @profile.twelvep %></div>
            </div><br>

            <div class="row">
              <div class="col-md-1 col-xs-1"><strong>Twelve College:</strong></div>
              <div class="col-md-2 col-xs-2"><%= @profile.twelvec %></div>
            </div><br>

            <div class="row">
              <div class="col-md-1 col-xs-1"><strong>Twelve Place:</strong></div>
              <div class="col-md-2 col-xs-2"><%= @profile.twelveplace %></div>
            </div><br>

            <div class="row">
              <div class="col-md-1 col-xs-1"><strong>Tenth Percentage:</strong></div>
              <div class="col-md-2 col-xs-2"><%= @profile.tenthp %></div>
            </div><br>

            <div class="row">
              <div class="col-md-1 col-xs-1"><strong>Tenth College:</strong></div>
              <div class="col-md-2 col-xs-2"><%= @profile.tenthc %></div>
            </div><br>

            <div class="row">
              <div class="col-md-1 col-xs-1"><strong>Tenth School:</strong></div>
              <div class="col-md-2 col-xs-2"><%= @profile.tenths %></div>
            </div><br>

            <div class="row">
              <div class="col-md-1 col-xs-1"><strong>Technical skills:</strong></div>
              <div class="col-md-2 col-xs-2"><%= @profile.technicalskills %></div>
            </div><br>

            <div class="row">
              <div class="col-md-1 col-xs-1"><strong>Nontechnical skills:</strong></div>
              <div class="col-md-2 col-xs-2"><%= @profile.nontechnicalskills %></div>
            </div><br>

            <div class="row">
              <div class="col-md-1 col-xs-1"><strong>Analytical skills:</strong></div>
              <div class="col-md-2 col-xs-2"><%= @profile.analyticalskills %></div>
            </div><br>

            <div class="row">
              <div class="col-md-1 col-xs-1"><strong>Projects:</strong></div>
              <div class="col-md-2 col-xs-2"><%= @profile.projects %></div>
            </div><br>

            <div class="row">
              <div class="col-md-1 col-xs-1"><strong>Courses taken:</strong></div>
              <div class="col-md-2 col-xs-2"><%= @profile.coursestaken %></div>
            </div><br>

            <div class="row">
              <div class="col-md-1 col-xs-1"><strong>Good at:</strong></div>
              <div class="col-md-2 col-xs-2"><%= @profile.goodat %></div>
            </div><br>

            <div class="row">
              <div class="col-md-1 col-xs-1"><strong>Dream job:</strong></div>
              <div class="col-md-2 col-xs-2"><%= @profile.dreamjob %></div>
            </div><br>

            <div class="row">
              <div class="col-md-1 col-xs-1"><strong>Awards:</strong></div>
              <div class="col-md-2 col-xs-2"><%= @profile.awards %></div>
            </div><br>

            <div class="row">
              <div class="col-md-1 col-xs-1"><strong>Internship:</strong></div>
              <div class="col-md-2 col-xs-2"><%= @profile.internship %></div>
            </div><br>
              <% @user = User.find_by(id: @profile.user_id) %>
              <% @email = Email.find_by(email: @user.email) %>
            <div class="row">
              <div class="col-md-1 col-xs-1"><strong>User Name:</strong></div>
              <div class="col-md-2 col-xs-2"><%= @email.user_name %></div>
            </div><br>
            <div class="row">
              <div class="col-md-1 col-xs-1"><strong>Email:</strong></div>
              <%= @email.email %> col-xs-2
            </div><br>
          </fieldset>
        </div>
      </div>
    </div>
  </div>
</section>